openapi: 3.0.3
info:
  title: Workers API - OpenAPI 3.0.3
  description: |-
    API to create, update and delete workers. A worker resource represents any employee, contractor or any kind of human capital.
  version: 1.0.0
paths:
  /workers:
    get:
      tags:
        - workers
      operationId: getWorkers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workers'
  /workers/{id}:
    get:
      tags:
        - worker
      operationId: getWorkerById
      parameters:
        - name: id
          in: path
          description: ID of worker
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        '400':
          description: Invalid ID supplied
        '404':
          description: Worker not found
components:
  schemas:
    Worker:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 18347239
        name:
          type: string
          example: full time, contractor, manager
        status:
          type: string
          description: worker status
          enum:
            - active
            - inactive
    Workers:
      type: object
      properties:
        workers:
          type: array
          items:
            $ref: '#/components/schemas/Worker'