openapi: 3.0.3
info:
  title: Policy Manager For Acquirers Sample API - OpenAPI 3.0
  description: |-
    Sample API for project PM4A to use as a POC.
  version: 1.0.0
paths:
  /policy:
    put:
      tags:
        - policy
      operationId: updatePolicy
      requestBody:
        description: Update an existing policy
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '400':
          description: Invalid ID supplied
        '404':
          description: Policy not found
        '405':
          description: Validation exception
    post:
      tags:
        - policy
      operationId: createPolicy
      requestBody:
        description: Create a new policy for acquirers
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Policy'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '405':
          description: Invalid input
  /policy/{policyId}:
    get:
      tags:
        - policy
      operationId: getPolicyById
      parameters:
        - name: policyId
          in: path
          description: ID of policy to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Policy'
        '400':
          description: Invalid ID supplied
        '404':
          description: Policy not found
components:
  schemas:
    Policy:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 18347239
        name:
          type: string
          example: Retail
        status:
          type: string
          description: policy status
          enum:
            - active
            - inactive
            - under review