openapi: 3.0.3
info:
  title: Workers API - OpenAPI 3.0.3
  description: |-
    API to create, update and delete workers. A worker resource represents any employee, contractor or any kind of human capital.
  version: 1.0.0
paths:
  /workers:
    put:
      tags:
        - policy
      operationId: updateWorker
      requestBody:
        description: Update an existing worker
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Worker'
        required: true
      responses:
        '200':
          description: Successful updated worker
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        '400':
          description: Invalid ID supplied
        '404':
          description: Worker not found
        '405':
          description: Validation exception
    post:
      tags:
        - Worker
      operationId: createWorker
      requestBody:
        description: Create a new worker
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Worker'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        '405':
          description: Invalid input
  /workers/{workerId}:
    get:
      tags:
        - worker
      operationId: getWorkerById
      parameters:
        - name: workerId
          in: path
          description: ID of worker
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Worker'
        '400':
          description: Invalid ID supplied
        '404':
          description: Worker not found
components:
  schemas:
    Worker:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 18347239
        name:
          type: string
          example: full time, contractor, manager
        status:
          type: string
          description: worker status
          enum:
            - active
            - inactive